name: Code formatter and linter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 'latest'

      - name: Install Dependencies
        run: |
          uv sync --locked --all-groups

      - name: Format with isort and black
        run: |
          uv run isort ./
          uv run black ./
      - name: Linting with ruff
        run: |
          uv run ruff check ./
      - name: Type Checking with pyright
        run: |
          uv run pyright ./
